name: dashpipe-build

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: macos-latest
            suffix: -mac
          - os: ubuntu-latest
            suffix: -linux
    env:
      zip_file: deco${{ matrix.suffix }}.zip

    steps:
      - uses: actions/checkout@v2

      - name: show ref
        run: |
          echo 1 $GITHUB_REF
          git show --oneline --no-patch

      - name: verify tag check
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        run: |
          echo "::error git checkout has no git tag"
          exit 1

      - name: Build
        run: cargo build --verbose --release

      - name: Run tests
        run: cargo test --verbose --release

      - name: package binary
        run: |
          cd target/release
          cp dashpipe deco
          zip ${{ env.zip_file }} deco

      - name: Release
        uses: softprops/action-gh-release@v0.1.13
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/release/${{ env.zip_file }}
